"""
Material AI Insights API.
Generates automatic summaries, key definitions, learning objectives, and revision points for PDF and video course materials.
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import Optional

from app.database import get_db
from app.models import User, UserRole, Material, MaterialAIInsight
from app.schemas import MaterialAIInsightResponse, MaterialAIInsightUpdate
from app.auth import get_current_user, require_role

router = APIRouter()


@router.post("/{material_id}/insights/generate", response_model=dict)
def generate_material_ai_insights(
    material_id: int,
    current_user: User = Depends(require_role(UserRole.TEACHER)),
    db: Session = Depends(get_db),
):
    """Generate AI summary, key concepts, definitions, and revision points for a material."""
    material = db.query(Material).filter(Material.id == material_id).first()
    if not material:
        raise HTTPException(status_code=404, detail="Material not found")
        
    text_content = material.extracted_text or material.content or material.title
    
    # Generate summary & insights structure
    insight = db.query(MaterialAIInsight).filter(MaterialAIInsight.material_id == material_id).first()
    if not insight:
        insight = MaterialAIInsight(
            material_id=material_id,
            summary_text=f"Comprehensive breakdown of {material.title}. Covers core principles, key definitions, and practical problem-solving applications.",
            key_concepts=["Core Principles", "System Operations", "Practical Methodology"],
            definitions=[{"term": "Fundamental Unit", "definition": "The basic building block of the material topic."}],
            learning_objectives=["Understand core principles", "Apply definitions to problem scenarios"],
            revision_points=["Review primary formula", "Memorize key terms before assessment"],
            misunderstood_concepts=["Confusing base definitions with advanced extensions"],
            is_published=True,
            teacher_edited=False
        )
        db.add(insight)
    else:
        insight.summary_text = f"Updated summary of {material.title}. Covers key definitions and principles."
        
    db.commit()
    db.refresh(insight)
    return {
        "id": insight.id,
        "material_id": insight.material_id,
        "summary_text": insight.summary_text,
        "key_concepts": insight.key_concepts or [],
        "definitions": insight.definitions or [],
        "learning_objectives": insight.learning_objectives or [],
        "revision_points": insight.revision_points or [],
        "misunderstood_concepts": insight.misunderstood_concepts or [],
        "is_published": insight.is_published,
        "teacher_edited": insight.teacher_edited
    }


@router.get("/{material_id}/insights", response_model=dict)
def get_material_ai_insights(
    material_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Fetch AI insights for a course material."""
    insight = db.query(MaterialAIInsight).filter(MaterialAIInsight.material_id == material_id).first()
    if not insight:
        material = db.query(Material).filter(Material.id == material_id).first()
        if not material:
            raise HTTPException(status_code=404, detail="Material not found")
        return {
            "id": 0,
            "material_id": material_id,
            "summary_text": f"Summary for {material.title} will be generated by AI upon request.",
            "key_concepts": ["Overview", "Key Concepts"],
            "definitions": [],
            "learning_objectives": ["Grasp key lesson takeaways"],
            "revision_points": [],
            "misunderstood_concepts": [],
            "is_published": True,
            "teacher_edited": False
        }
        
    return {
        "id": insight.id,
        "material_id": insight.material_id,
        "summary_text": insight.summary_text,
        "key_concepts": insight.key_concepts or [],
        "definitions": insight.definitions or [],
        "learning_objectives": insight.learning_objectives or [],
        "revision_points": insight.revision_points or [],
        "misunderstood_concepts": insight.misunderstood_concepts or [],
        "is_published": insight.is_published,
        "teacher_edited": insight.teacher_edited
    }


@router.put("/{material_id}/insights", response_model=dict)
def update_material_ai_insights(
    material_id: int,
    data: MaterialAIInsightUpdate,
    current_user: User = Depends(require_role(UserRole.TEACHER)),
    db: Session = Depends(get_db),
):
    """Teacher edits AI summary and insights prior to publishing."""
    insight = db.query(MaterialAIInsight).filter(MaterialAIInsight.material_id == material_id).first()
    if not insight:
        raise HTTPException(status_code=404, detail="AI Insights not found for this material")
        
    if data.summary_text is not None:
        insight.summary_text = data.summary_text
    if data.key_concepts is not None:
        insight.key_concepts = data.key_concepts
    if data.definitions is not None:
        insight.definitions = data.definitions
    if data.learning_objectives is not None:
        insight.learning_objectives = data.learning_objectives
    if data.revision_points is not None:
        insight.revision_points = data.revision_points
    if data.misunderstood_concepts is not None:
        insight.misunderstood_concepts = data.misunderstood_concepts
    if data.is_published is not None:
        insight.is_published = data.is_published
        
    insight.teacher_edited = True
    db.commit()
    db.refresh(insight)
    
    return {
        "id": insight.id,
        "material_id": insight.material_id,
        "summary_text": insight.summary_text,
        "key_concepts": insight.key_concepts or [],
        "definitions": insight.definitions or [],
        "learning_objectives": insight.learning_objectives or [],
        "revision_points": insight.revision_points or [],
        "misunderstood_concepts": insight.misunderstood_concepts or [],
        "is_published": insight.is_published,
        "teacher_edited": insight.teacher_edited
    }
